---
title: "CLASSCODE"
author: "JEFFERSON SARANSIG"
date: "2026-08-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#install.packages("janitor")
library(tidyverse)
library(gridExtra)
library(janitor)
```

## Winter CH 1
code from ch 1 of winter textbook
```{r}
numbers <- c(18, 200, 92, 14)
sum(numbers)
mean(numbers)
sd(numbers) %>% round(digits = 2) #the "digits = " se usa solo para recordarnos, en realidad se puede hacer solo round(2). "%>%" help us string operations
names <- c("a", "b", "c")
names

```



```{r}
list.files()
head(nettle) #head() shows the first few rows of a data frame
nettle <- read.csv('nettle_1999_climate.csv')
head(nettle)
tail(nettle) #head() shows the last few rows of a data frame
```


```{r}
hist(nettle$Langs) # the $ operator extracts a specific column (or list element) by name from a data frame or list.
hist(nettle$Langs, col = 'salmon')
```

```{r}
hist(nettle$Langs, col = 'steelblue')
```
```{r}
x_values <- c(1, 2, 3, 4, 5, 6, 7, 8, 9)
mean_x <- mean(x_values)
mean_x #para sacar el valor de la media
```

```{r}
x <- c(2, 3, 4, '4')
x <- as.numeric(x)
mean(x)

```

```{r}
head(nettle)
nettle[2,5]
nettle[1:4, 1:2]
nettle[nettle$Country == 'Bangladesh', 'Langs']
nettle[1:4, ]$Langs[2]
nettle[1:4, c('Country', 'Langs')]
head(nettle[,])

```

```{r}
# Load data:
nettle <- read.csv('nettle_1999_climate.csv') #"read.csv" is part of Base R

# Convert data frame to tibble:
nettle <- as_tibble(nettle)
nettle
```

```{r}
nettle <- read_csv('nettle_1999_climate.csv')

```
```{r}
nettle

```

```{r}
ggplot(nettle) +
geom_point(mapping = aes(x = MGS, y = Langs)) # "mapping" can be omitted
```

```{r}
ggplot(nettle, aes(x = Population, y = Area)) +
  geom_point()
```

```{r}
nettle%>%filter(Area > 6)
```


```{r}
ggplot(nettle, aes(x = MGS, y = Langs, label = Country)) +
geom_text()
```


```{r}
ggsave('nettle.png', width = 8, height = 6)
```

```{r}
# Create plots and save them in plot1 and plot2:
plot1 <- ggplot(nettle) +
geom_point(mapping = aes(x = MGS, y = Langs))
plot2 <- ggplot(nettle,
aes(x = MGS, y = Langs, label = Country)) +
geom_text()
# Plot double plot:
library(gridExtra)
grid.arrange(plot1, plot2, ncol = 2)
```
```{r}
# Create plots and save them in plot1 and plot2:
plot1 <- ggplot(nettle) +
geom_point(mapping = aes(x = MGS, y = Langs))
plot2 <- ggplot(nettle,
aes(x = MGS, y = Langs, label = Country)) +
geom_text()
# Plot double plot:
library(gridExtra)
grid.arrange(plot1, plot2, ncol = 2)
```

```{r}
# Plotting pipeline with %>%:
nettle %>%
filter(MGS > 8) %>%
ggplot(aes(x = MGS, y = Langs, label = Country)) +
geom_text()
```

```{r}
str(nettle) # base R inspect the dataframe
glimpse(nettle) #tidyverse inspect the dataframe

```


Exercises from textbook 2.11.3-4
```{r}
head(nettle)
```
```{r}
filter(nettle, Country == 'Benin')
```
```{r}
filter(nettle, Country %in% c('Benin', 'Zaire')) #checks whether each value in a vector matches any value in a set of values — it returns TRUE/FALSE for each element
```
```{r}
select(nettle, Langs)
```

```{r}
filter(nettle, Country == 'Benin') %>% select(Langs)
```
```{r}
filter(nettle, Country == 'Benin') %>%
select(Population:MGS)
```
```{r}
filter(nettle, Langs > 200)
```
```{r}
filter(nettle, Langs > 200, Population < median(Population)) #Population < median(Population) means:Keep only countries whose population is below the median population of the whole dataset
```
```{r}
median(nettle$Population) #in this case we need $ not comma as meadian takes one specific colum from the data frame
```

